spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ENC(OM5TH03IFE3wOtQWpgfv/vlav8LjpLL1w38Ghi7roSlMYsTLahyO4cbz8rPVoSkuOVGSphZWnwU6XESatLiJGAn2e84VCtk/0jxYwnxIscF+aZJNjOge/V5irZEPZXRtbud7rUeJU3idhqDPQ6q9enoz0rN4B7tQHJoWQ1cslaY=)
    username: ENC(VhV1Y8nhaVU7DFTVjkZSfQs+XWAi3Op+)
    password: ENC(qGtan+Xel4BBnPtrne9ZrR0SLy+7Bw6RDAWTD/p6Xc0=)
  application:
    name: genius-blog-main

assistant:
  service:
    exception:
      handler:
        disables: springWebExceptionHandler

