spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ENC(ZJD30apv0TnJnjbVWj/W5iEdsp69bwugrfGWqnEpVXhZ9hhZwSVLDTHt51MBrGT7mIoQxj6+XxWRZNoE+KypedyMY6+FLocV49SPot7BSX9eO24/Li1IOmDy4LHc2g2H5QaK59GOZ+xDNyLT40c5QS7TQCJnjLJkppWDjm48MT0=)
    username: ENC(VhV1Y8nhaVU7DFTVjkZSfQs+XWAi3Op+)
    password: ENC(JdU9LZdyBdiF029widwkA/v0+KZB/9iUWeGALxI9ndENUlzNZMH+BQ==)
  mail:
    host: ${EMIAL_HOST:ENC(qMKUwBybaAKewuGZCDYjQw6tCfRVAO5aIQUolS8L06U=)}
    port: ${EMAIL_PORT:ENC(7RRjEe4cBjcETAkyZ6TBh5zwIw6KrEaz)}
    username: ${EMAIL_USERNAME:ENC(Ndpes2aPfHdQQLG2Ds47yIxEh5/YB2ywTbf7UZ8Re7JgCTjwemDMQw==)}
    password: ${EMAIL_PASSWORD:ENC(IFKjNrj7WUsXTiTldZ8TDgHxBxgkYHXBD5RrrjZ2SlGFXMCaObgqgA==)}
    test-connection: false

  application:
    name: genius-blog-main

assistant:
  service:
    exception:
      handler:
        disables: springWebExceptionHandler

captcha:
  mail:
    code-length: 6
  image-code:
    width: 180
    height: 40
    dot-size: 50

point:
  reset:
    key: ${RESET_KEY:ENC(OmgmeMPeP3TRvg6n9Mc8LKaFN51DjuT8nVVfc79PQPE==)}

AIGenerate:
  API_KEY: ${"API_KEY":ENC(li21ByYLAg/rKbFgMaufT+7PbsTYmdJSDusGI2Y7483pQdpXHvBRPgt78dfGQgybBqQKZnR9Mfs=)}
  STRATEGY: ${"DEFAULT_STRATEGY":qw}

