spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ENC(eIWk8LT/09kZkJBt9ffzpQwqgwZOJtPx551qDudya+Sz6qH80fXL8YKNKAjVfzlbh4MpahqTcKp+p+2XkLk4t1st1TkxksvMxXvLBFiswIm0zLWVNEDTZ0LudtsBtjqHFCjzDsDTlovOvq0QDZtQpgwe/jme3CK3rxQBX1r3BCrsePX6zZ5lqADq/NOwbsyJ)
    username: ENC(kwCqh4NJB/GHhj8ujEHEA2z7bi33eiJ5)
    password: ENC(4y+DP8TGA5RYUSQWk9QzWWL8jY6rcdUp4IRCyYmsxKE=)
    type: com.zaxxer.hikari.HikariDataSource # 使用 HikariCP 连接池
    hikari:
      minimum-idle: 10
      maximum-pool-size: 100
      idle-timeout: 600000
      pool-name: DatebookHikariCP
      max-lifetime: 120000
      connection-timeout: 30000
#      connection-test-query: SELECT 1

  mail:
    host: ${EMIAL_HOST:ENC(qMKUwBybaAKewuGZCDYjQw6tCfRVAO5aIQUolS8L06U=)}
    port: ${EMAIL_PORT:ENC(7RRjEe4cBjcETAkyZ6TBh5zwIw6KrEaz)}
    username: ${EMAIL_USERNAME:ENC(Ndpes2aPfHdQQLG2Ds47yIxEh5/YB2ywTbf7UZ8Re7JgCTjwemDMQw==)}
    password: ${EMAIL_PASSWORD:ENC(IFKjNrj7WUsXTiTldZ8TDgHxBxgkYHXBD5RrrjZ2SlGFXMCaObgqgA==)}
    test-connection: false
  redis:
    host: ${REDIS_HOST:ENC(ihqkERXHQPC78a4vRkhcQzO5M/OEM1C7c63/HsY0knk=)}
    port: ${REDIS_PORT:ENC(wWO0eu+D3AMU5Lc8N0f9w6YkKlVahAOi)}
    database: 10
    password: ${REDIS_PASSWORD:ENC(BHR/Bl0sDcqkiZmNzKQQmFBPKpkLLTVezejyKGAwNeo=)}
    lettuce:
      pool:
        max-active: 8 # 最大连接数
        max-wait: -1ms # 连接池最大阻塞等待时间（负数表示不限制）
        max-idle: 8 # 最大空闲连接数
        min-idle: 0 # 最小空闲连接数
    connect-timeout: 10000

  application:
    name: genius-blog-main

assistant:
  service:
    exception:
      handler:
        disables: springWebExceptionHandler


captcha:
  mail:
    code-length: 4
  image-code:
    width: 180
    height: 40
    dot-size: 50

AIGenerate:
  API_KEY: ${"API_KEY":ENC(li21ByYLAg/rKbFgMaufT+7PbsTYmdJSDusGI2Y7483pQdpXHvBRPgt78dfGQgybBqQKZnR9Mfs=)}
  STRATEGY: ${"DEFAULT_STRATEGY":qw}

point:
  reset:
    key: ${RESET_KEY:ENC(gTMJIBjg+TP1EZsMJzrjez8Lipi5aJL/dPvfOsR1FR3TcAIuRy6qMA==)}

Schedule:
  STRATEGY: ${DEFAULT_STRATEGY:freeRobot}


bilibili:
  video:
    init-on-startup: false
